---
source: this_week
type: video
url: http://www.imdb.com/movies-in-theaters/
items_selector: '[itemtype="http://schema.org/Movie"]'
title_selector: '[itemprop="name"]'
genre_selector: '[itemprop="genre"]'
image_selector: '[itemprop="image"]'
synopsis_selector: '[itemprop="description"]'
---
source: comming_soon
type: video
url: http://www.imdb.com/movies-coming-soon/
items_selector:
    - '[itemtype="http://schema.org/Movie"]'
    - 0
title_selector: '[itemprop="name"]'
genre_selector: '[itemprop="genre"]'
image_selector: '[itemprop="image"]'
synopsis_selector: '[itemprop="description"]'
---
source: top_100_brazilian_musics
type: audio
url: http://www.hot100brasil.com/chtsinglesb.html
items_selector: 'tr[height=19]'
name_selector:
   selector: 'td'
   position: 4
artist_selector:
   selector: 'td'
   position: 5
label_selector:
   selector: 'td'
   position: 6
